language: r

sudo: false

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    - secure: "CwEV0N2IeRQBqD7T6uiZmqpw4orE34RDSsouoqmbyb1mWDFYXXPYofdb67YgGXchcgtlC90VhtVVJ2ea57wXpumHebFjPG5lp1OJm3S4p4O1iXiTS/33PE7sLUkotzL2aOiI5p/yYQfoF9uFoO6dFuxWxFTa0oU8OnAB46YoLWA="

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended

install:
  - # "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"

cache:
  directories:
  - $HOME/R

script:
  - # docs
  - pwd
  - cd ./docs
  - Rscript -e "devtools::install_github('rstudio/bookdown')"
  - pwd
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - git config --global user.email "happy@langdawei.com"
  - git config --global user.name "Dawei Lang"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/taiyun/recharts.git book-output
  - cd book-output
  - cp -r ../_book/* ./
  - git add --all *
  - git commit -m"Update the book" || true
  - git push -q origin gh-pages
  - cd ../..
  - # buid & check
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - # set -e
  - # "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
  - pwd
